name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt
      - name: Generate KPIs (builds docs/data/kpi.json)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python scripts/generateAutomationKpis.py
      - name: Run tests
        env:
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: 1
          PYTHONPATH: ${{ github.workspace }}
        run: python -m pytest -q
